# Generated by Django 5.2.7 on 2025-10-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre_editorial', max_length=100)),
                ('pais', models.CharField(db_column='pais_editorial', max_length=50)),
                ('calle', models.CharField(blank=True, db_column='calle_editorial', max_length=100, null=True)),
                ('numero_calle', models.IntegerField(blank=True, db_column='numero_calle_editorial', null=True)),
                ('casa', models.BooleanField(db_column='casa_editorial', default=False)),
                ('edificio', models.BooleanField(db_column='edificio_editorial', default=False)),
                ('piso', models.CharField(blank=True, db_column='piso_editorial', max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, db_column='departamento_numero_casa_editorial', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
