# Generated by Django 5.2.7 on 2025-10-14 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores', '0001_initial'),
        ('categorias', '0001_initial'),
        ('editoriales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_column='titulo_libro', max_length=200)),
                ('fecha_publicacion', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(db_column='nombre_autor', on_delete=django.db.models.deletion.CASCADE, to='autores.autor')),
                ('categoria', models.ForeignKey(db_column='nombre_categoria', on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
                ('editorial', models.ForeignKey(db_column='nombre_editorial', on_delete=django.db.models.deletion.CASCADE, to='editoriales.editorial')),
            ],
        ),
    ]
